### ISSUE TITLE
m_robot数据库相关

### ISSUE THREAD

**Issue by andywong2019** [yangjinhe/maintain-robot#1]
db数据库账号密码在哪设置呢，建表sql有吗

[ERROR] 10:10:52.067 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2336) - create connection SQLException, url: jdbc:mysql://127.0.0.1:3306/m_robot, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'robot'@'localhost' (using password: YES)

**Comment by yangjinhe** [comment]
resources/ioc文件夹里面有一个dao.js 里面可以修改数据库连接。不需要建表语句，启动会自动建表
